name: ftp-transfer

on:
  push:
    branches: [ remote-integration ]

jobs:
  ftp-transfer:
    runs-on: ubuntu-latest

    steps:
      - name: Set up FTP client
        run: sudo apt install lftp

      - name: Upload files to FTP server
        run: sudo lftp -u ${{secrets.FTP_USERNAME}},${{secrets.FTP_PASSWORD}} -p 21 ${{secrets.FTP_SERVER}}  -e 'set ftp:ssl-force yes; set ssl:verify-certificate yes;      mirror        --verbose --reverse --only-newer ./webpage /ismgroup39/test;      bye'
          
